colorScheme = "fire"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true
mainSections = ["posts"]

[author]
  name = "Jiahao Chen"
  email = "jiahaochen535@gmail.com"
  headline = "Gotta Read Em All"
  bio = "每日收集财经、科技、足球、论文情报的训练师日志"
  links = [
    { github = "https://github.com/can-gaa-hou" }
  ]

[homepage]
  layout = "page"
  showRecent = true
  showRecentItems = 20
  showMoreLink = false
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = false
  showReadingTime = true
  showWordCount = false
  showBreadcrumbs = false
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showTaxonomies = true
  showTableOfContents = true
  sharingLinks = []

[list]
  showBreadcrumbs = false
  showSummary = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[taxonomy]
  showTermCount = true
  cardView = true
